let libertyWalk = {
  customKits: [
    {
      NISSAN: [
        {
          typeOfKits: [
            {
              completeBodyKit: 17,
              priceRange: [
                {
                  SilhouetteWorksGTRR: "$33480 - $54540",
                  lbStarWorksNissanGTR: "$20690 - 26900",
                  SuperSilhouetteWorksNissanSilvia: "$25135",
                },
              ],
            },
            {
              bodyKitWorks: 22,
              priceRange: [
                {
                  lbStarSilhouetteWorks35GtrrWing: "$6480 - $15250",
                  lbStarSilhouetteWorks35GtrrBonnetHood: "$2700 - $8100",
                  lbStarSilhouetteWorks35GtrrFrontBumper: "$3780 - $7020",
                },
              ],
            },
          ],
        },
      ],

      TOYOTA: [
        {
          typeOfKits: [
            {
              completeBodyKit: 6,
              priceRange: [
                {
                  lbStarWorksToyotaLandCruiser300PremiumCompleteKit:
                    "$13090 - $34430",
                  lbStarWorksToyotaSupraA90CompleteBodyKit: "$14850 - 20130",
                  lbStarNationToyotaGR86BodyKitWorksWorks: "$7810 - $9130",
                  lbStarNationToyota86V1BodyKit: "$5340 - $5770",
                  lbStarNationToyota86V2BodyKit: "$4470 - $4900",
                  lbStarNationKBreak18ToyotaCrownWorksFullBodyKit: "$4620",
                },
              ],
            },
            {
              bodyKitWorks: 18,
              priceRange: [
                {
                  lbStarWorksToyotaSupraA90RearWing: "$3850 - $6050",
                  lbStarNationToyotaGr86ZN8RearGtWingV1: "$2530 - $3850",
                  lbStarWorksToyotaSupraA90RearDiffuserAndRearSideFin: "$3300",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
