// brand: NISSAN, numberOfKits: 37, priceRange: 540 - 55450
// brand: PORSCHE, numberOfKits: 4, priceRange: 4500 - 20300
// brand: TOYOTA, numberOfKits: 24, priceRange: 330 - 34430

function function1() {
  let libertyWalk = {
    customKits: [
      {
        NISSAN: [
          {
            typeOfKits: [
              {
                completeBodyKit: 17,
                priceRange: [
                  {
                    SilhouetteWorksGTRR: "$33480 - $54540",
                    lbStarWorksNissanGTR: "$20690 - 26900",
                    SuperSilhouetteWorksNissanSilvia: "$25135",
                  },
                ],
              },
              {
                bodyKitWorks: 22,
                priceRange: [{}],
              },
            ],
          },
        ],
        PORSCHE: [
          {
            typeOfKits: [
              {
                completeBodyKit: 1,
              },
              {
                bodyKitWorks: 3,
              },
            ],
          },
        ],
        TOYOTA: [
          {
            typeOfKits: [
              {
                completeBodyKit: 3,
              },
              {
                bodyKitWorks: 21,
              },
            ],
          },
        ],
      },
    ],
  };
}
